

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.tjwhwqlqkwbaidgkzofu
spring.datasource.password=C$#5jwpeHashHR.

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.auto-commit=false

spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG

jwt.secet=${JWT_SECRET}
jwt.expiration-ms=3600000



