

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.tjwhwqlqkwbaidgkzofu
spring.datasource.password=C$#5jwpeHashHR.

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true



